### ISSUE TITLE
Remove a hook

### ISSUE THREAD

**Issue by Xanderplayz16** [chilaxan/fishhook#12]
If I hooked a function into list (list.xyz), how would I remove list.xyz? I can't del it, and I cannot find any way to do it via fishhook.

**Comment by chilaxan** [comment]
Assuming the hook was made with the decorator like below: 
```py
@hook(list)
def xyz(self, ...):
   ...
```
Then you can use `unhook(list, 'xyz')` to remove the hook. 

If there are stacked hooks, then unhook should remove the most recent hook.

**Comment by Xanderplayz16** [comment]
Thanks!
