### ISSUE TITLE
Issue with `orig()` called from hooked `type.__prepare__` ?

### ISSUE THREAD

**Issue by greyblue9** [chilaxan/fishhook#2]
Reproducer:
```py
from fishhook import hook, orig
@hook(type, "__prepare__")
def __prepare__(self,*a,**kw):
    print("__prepare__", self, a, kw)
    c = orig(self,*a,**kw)
    print(c)
    return c

class C: pass
```

I get the following error:

```__prepare__ C ((),) {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in __prepare__
  File "/usr/local/lib/python3.9/dist-packages/fishhook/__init__.py", line 116, in orig
    raise RuntimeError('no original method found')
RuntimeError: no original method found
```

Thoughts?

Really love the package. I'm probably just using it wrong :)
--David

**Comment by chilaxan** [comment]
found the issue, `__prepare__` is passed the following args: cls_name, cls_bases, cls_mapping. Its treated as a class method. `orig` relies on the first argument passed being an instance of the class hooked (to make it cleaner to use) so it currently will not work for methods like this. as a work around you can grab the original implementation by doing `fishhook.methods_cache[f'{id(type)}'.__prepare__]` this probably wont be fixed (unless i can find a way to store the relevant information for original method calling on the code object)

**Comment by chilaxan** [comment]
I'll leave this open for now

**Comment by greyblue9** [comment]
> found the issue, `__prepare__` is passed the following args: cls_name, cls_bases, cls_mapping. Its treated as a class method. `orig` relies on the first argument passed being an instance of the class hooked (to make it cleaner to use) so it currently will not work for methods like this. as a work around you can grab the original implementation by doing `fishhook.methods_cache[f'{id(type)}'.__prepare__]` this probably wont be fixed (unless i can find a way to store the relevant information for original method calling on the code object)

wow, thank you for the quick answer! I was just hpping to determine if I am just cursed ot if this was just an edge case of some kind. Sounds like #2 

I actually added a bunch of debugging to `__init__.py` to understand the situation and noticed `orig` was looking in the `str` class for the original function, but couldn't think of a way to obtain the correct one :D

**Comment by greyblue9** [comment]
Just out of curiosity, will it always be `type.__prepare__`?  Or could it be some other (instance or subclass of)  `type`?

**Comment by chilaxan** [comment]
Seems that because `__prepare__` is handled like a class method this will always happen

**Comment by greyblue9** [comment]
> Seems that because `__prepare__` is handled like a class method this will always happen

I think I follow. I hacked around a bit and got something thaalmost works but it calls the hook twice one with a string and one with the actual class (type)

**Comment by greyblue9** [comment]
I think you can close this. I was able to get it to work by doing:
```py
import fishhook
@fishhook.hook(type, "__prepare__")
@classmethod
def __prepare__(cls,name,bases,**kw):
    print(f"__prepare__({name=}, {bases=}, {kw=})")
    c = fishhook.orig(cls,name,bases,**kw)
    print(c)
    return c
```

I do hit two small mro issues, but using `type.mro.__get__(cls)()` instead of `cls.mro()` fixes both places and I get the (correct?) output:


```
__prepare__(name='C', bases=(), kw={})
{}
```
