### ISSUE TITLE
Overriding int.__add__ gives recursion error

### ISSUE THREAD

**Issue by washad** [chilaxan/fishhook#4]
Thanks for the awesome tool and for your hard work in creating it;  

In Python 3.9 (haven't tried others) the example gives a recursion error; 

```
from fishhook import hook, hook_cls, orig

@hook(int)
def __add__(self, other):
    ...
    return orig(self, other)


if __name__ == '__main__':
    print(3 + 4)
```

`RecursionError: maximum recursion depth exceeded while calling a Python object`

Note, if I don't use `orig`, I get a segfault

```
@hook(int)
def __add__(self, other):
    return 35
```
`
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by chilaxan** [comment]
Just tested on 3.9.12 and did not notice any issues, what is the minor version you are testing on?

**Comment by washad** [comment]
Python 3.9.13

**Comment by washad** [comment]
It actually kind of makes sense -- I see in an `itos` method in your code, the following `yield chr(n % 10 + 48)` -- which is doing addition, thus calling __add__ again. Maybe I'm missing in the docs, but how would I patch everything BUT your code?

**Comment by chilaxan** [comment]
so right now fishhook patches everything globally, since its happening at the C level. It's tricky to limit the hooks to a specific scope. to fix this specific bug you can add a line at the beginning of `__init__` to store `int.__add__` and then use it at that spot. I might write some code to just cache all dunders within fishhook at compile time and just use the stored methods exclusively but it will be a while till i have time

**Comment by washad** [comment]
Unfortunately, calling original `int.__add__`  Doesn't make it work either; There is a post on it here; https://mcla.ug/blog/cpython-hackage.html

```
from fishhook import hook, hook_cls, orig


@hook(int)
def __add__(self, other):
    return 35


if __name__ == '__main__':
    print((3).__add__(4))    # Gives 35
    print(3+4)   # Gives 7
```

There is something very unique about base math operations, it seems. May just be best to note that in the documentation and change the example code?

**Comment by chilaxan** [comment]
I'll work on a solution later today or tomorrow

**Comment by chilaxan** [comment]
0.2.1 (just released) should fix this issue
